import Foundation

@main
struct FileShelfStoreChecks {
    @MainActor static func main() async throws {
        let root = FileManager.default.temporaryDirectory.appending(path: "smool-shelf-store-\(UUID())")
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }
        let first = root.appending(path: "first.txt")
        let second = root.appending(path: "second.txt")
        try Data().write(to: first)
        try Data().write(to: second)
        let storage = root.appending(path: "shelf.json")
        let store = FileShelfStore(storageURL: storage)
        store.refresh()
        store.add(urls: [first])
        store.add(urls: [second])
        await store.finishPendingChanges()
        precondition(store.files.map(\.reference.name) == ["second.txt", "first.txt"])
        precondition(!store.isLoading && store.error == nil)
        store.moveSelection(100)
        precondition(store.selectedFile?.reference.name == "first.txt")
        store.moveSelection(-100)
        precondition(store.selectedFile?.reference.name == "second.txt")
        store.remove(id: store.selectedFile!.id)
        store.refresh()
        await store.finishPendingChanges()
        precondition(store.selectedFile?.reference.name == "first.txt")
        precondition(FileManager.default.fileExists(atPath: second.path))
        let restored = FileShelfStore(storageURL: storage)
        restored.refresh()
        await restored.finishPendingChanges()
        precondition(restored.files.map(\.id) == store.files.map(\.id))

        let third = root.appending(path: "third.txt")
        let fourth = root.appending(path: "fourth.txt")
        try Data().write(to: third)
        try Data().write(to: fourth)
        store.add(urls: [second, third, fourth])
        await store.finishPendingChanges()
        let ids = store.files.map(\.id)
        precondition(ids.count == 4)
        store.select(ids[0])
        store.select(ids[2], toggling: true)
        precondition(store.selectedIDs == [ids[0], ids[2]])
        precondition(store.selectedURLs.map { $0.resolvingSymlinksInPath() } == [second, fourth].map { $0.resolvingSymlinksInPath() })
        store.select(ids[2], toggling: true)
        precondition(store.selection == ids[0] && store.selectedIDs == [ids[0]])
        store.select(ids[0])
        store.select(ids[2], extending: true)
        precondition(store.selectedIDs == Set(ids[0...2]))
        store.select(ids[1], extending: true)
        precondition(store.selectedIDs == Set(ids[0...1]))
        store.select(ids[3], extending: true, toggling: true)
        precondition(store.selectedIDs == Set(ids))
        store.select(ids[1])
        store.moveSelection(1, extending: true)
        precondition(store.selectedIDs == Set(ids[1...2]))
        store.moveSelection(-1, extending: true)
        precondition(store.selectedIDs == [ids[1]])
        store.select(ids[1], toggling: true)
        precondition(store.selectedIDs.isEmpty && store.selectedFile == nil)
        store.refresh()
        await store.finishPendingChanges()
        precondition(store.selectedIDs.isEmpty && store.selectedFile == nil)
        store.selectAll()
        precondition(store.selectedURLs.map { $0.resolvingSymlinksInPath() } == [second, third, fourth, first].map { $0.resolvingSymlinksInPath() })
        store.removeSelected()
        await store.finishPendingChanges()
        precondition(store.files.isEmpty && store.selectedIDs.isEmpty && store.selection == nil)
        precondition([first, second, third, fourth].allSatisfy { FileManager.default.fileExists(atPath: $0.path) })

        let blockedPath = root.appending(path: "not-a-directory")
        try Data().write(to: blockedPath)
        let blocked = FileShelfStore(storageURL: blockedPath.appending(path: "shelf.json"))
        blocked.add(urls: [first])
        await blocked.finishPendingChanges()
        precondition(blocked.error != nil)
        precondition(blocked.files.isEmpty)
        precondition(FileManager.default.fileExists(atPath: first.path))
        print("File shelf queued writes, range/toggle selection, multi-file payloads, removal, restore and storage failure passed")
    }
}
